### ISSUE TITLE
Create and migrate RTE 3.0.0 docs to gitbook

### ISSUE THREAD

**Issue by pwrinc** [cubbles/gitbook#6]
The documention for the RTE needs to be migrated from confluence wiki to our gitbook.com cubbles space. Where necessary the RTE documentation needs to be adjusted to include changes/new features in RTE 3.0.0

__Note:__ I just triggerd a new request for an open source licence at gitbook.com for our Cubbles space there

### Docs to migrate/adapt
- [x] 2.4 | User Guide
- [x] 2.4 | RTE Integration
- [x] 2.4 | The Cubbles Tag API
- [x] 2.4 | The Cubbles Dependency API
- [x] 2.4 | The Cubbles IFrame API
- [x] 2.4 | The Cubbles IFrame Resizer API
- [x] 2.4 | The Cubbles Javascript API
- [x] 2.4 | RTE processing
- [x] 2.4 | RTE initialization and rendering timeline
- [x] 2.4 | The Cubbles Mutation Based Startevent API
- [x] 2.4 | FAQs
- [x] 2.4 | FAQ: How to manually resolve dependency conflicts?
- [x] 2.4 | How to create a component instance dynamically?
- [x] 2.4 | How to create nested component instances dynamically within elementary Cubbles components _(Not necessary, since it was special due to the use of Polymer in elementary components)_
- [x] 2.4 | How to render HTML Markup coming from input slot?
- [x] 2.4 | How to replace a dependency when declaring a component instance?
- [x] 2.4 | How to synchronize multiple data flows between component instances?
- [x] 2.4 | How to handle the copyValue flag for non serializable instances?
- [x] 2.4 | Contributors Guide
- [x] 2.4 | CIF processing
- [x] 2.4 | Cubbles Dependency Management (See #7)

**Comment by edwingamboa** [comment]
@pwrinc what exactly are we meant to write here? https://cubbles.atlassian.net/wiki/spaces/RTE/pages/20524588/2.4+Cubbles+Dependency+Management

**Comment by pwrinc** [comment]
The idea was to explain the cubbles dependency mechanism in detail. This will be a task for myself. But I think due to time restrictions you can skip this section for now.

**Comment by edwingamboa** [comment]
Okay @pwrinc, I created a new issue and assigned to you (#7).
